"""Public entrypoint for the Onyx Database Python SDK."""

from .config import WireFormat
from .errors import (
    OnyxConfigError,
    OnyxHTTPError,
    OnyxUnauthorizedError,
    OnyxNotFoundError,
    OnyxRateLimitedError,
    OnyxClientError,
    OnyxServerError,
    OnyxTimeoutError,
)
from .onyx import OnyxFacade, onyx
from .helpers.conditions import (
    approximate_candidates,
    approximate_search,
    eq,
    neq,
    within,
    not_within,
    in_op,
    not_in,
    between,
    not_between,
    gt,
    gte,
    lt,
    lte,
    like,
    not_like,
    contains,
    not_contains,
    starts_with,
    not_starts_with,
    matches,
    not_matches,
    is_null,
    not_null,
    search,
    hnsw_candidates,
)
from .helpers.candidate_search import (
    DEFAULT_APPROXIMATE_INDEX_CANDIDATES,
    DEFAULT_HNSW_CANDIDATES,
    DEFAULT_HNSW_EF_SEARCH,
    HNSW_QUERY_FORMAT_VERSION,
    MAX_APPROXIMATE_INDEX_CANDIDATES,
    MAX_APPROXIMATE_INDEX_ROUTE_VALUES,
    MAX_HNSW_CANDIDATES,
    MAX_HNSW_EF_SEARCH,
    MAX_HNSW_VECTOR_DIMENSION,
    MAX_VECTOR_SEARCH_CANDIDATES,
    approximate_index_candidate_query,
    hnsw_search_query,
    semantic_vector_signature,
    vector_search_query,
)
from .helpers.sort import asc, desc
from .onyx_async import OnyxAsyncFacade, onyx_async
from .types import (
    ApproximateIndexCandidateQuery,
    ApproximateSearchOptions,
    FullTextQuery,
    HnswSearchQuery,
    HnswSearchQueryInput,
    Int64WireInput,
    QueryCriteriaOperator,
    SearchMatch,
    SearchMode,
    SearchOptions,
    SemanticVectorSignature,
    SemanticVectorSignatureInput,
    VectorSearchQuery,
    VectorSearchQueryInput,
)
from .helpers.aggregates import (
    avg,
    sum,
    count,
    min,
    max,
    std,
    variance,
    median,
    upper,
    lower,
    substring,
    replace,
    format,
    percentile,
)

__all__ = [
    "OnyxFacade",
    "OnyxAsyncFacade",
    "onyx",
    "onyx_async",
    "WireFormat",
    "OnyxConfigError",
    "OnyxHTTPError",
    "OnyxUnauthorizedError",
    "OnyxNotFoundError",
    "OnyxRateLimitedError",
    "OnyxClientError",
    "OnyxServerError",
    "OnyxTimeoutError",
    # conditions
    "eq",
    "neq",
    "within",
    "not_within",
    "in_op",
    "not_in",
    "between",
    "not_between",
    "gt",
    "gte",
    "lt",
    "lte",
    "like",
    "not_like",
    "contains",
    "not_contains",
    "starts_with",
    "not_starts_with",
    "matches",
    "not_matches",
    "is_null",
    "not_null",
    "search",
    "approximate_search",
    "hnsw_candidates",
    "approximate_candidates",
    # native candidate-search wire helpers
    "HNSW_QUERY_FORMAT_VERSION",
    "DEFAULT_HNSW_CANDIDATES",
    "DEFAULT_HNSW_EF_SEARCH",
    "MAX_HNSW_CANDIDATES",
    "MAX_HNSW_EF_SEARCH",
    "MAX_HNSW_VECTOR_DIMENSION",
    "DEFAULT_APPROXIMATE_INDEX_CANDIDATES",
    "MAX_APPROXIMATE_INDEX_CANDIDATES",
    "MAX_APPROXIMATE_INDEX_ROUTE_VALUES",
    "MAX_VECTOR_SEARCH_CANDIDATES",
    "semantic_vector_signature",
    "vector_search_query",
    "hnsw_search_query",
    "approximate_index_candidate_query",
    # public search types
    "ApproximateIndexCandidateQuery",
    "ApproximateSearchOptions",
    "FullTextQuery",
    "HnswSearchQuery",
    "HnswSearchQueryInput",
    "Int64WireInput",
    "QueryCriteriaOperator",
    "SearchMatch",
    "SearchMode",
    "SearchOptions",
    "SemanticVectorSignature",
    "SemanticVectorSignatureInput",
    "VectorSearchQuery",
    "VectorSearchQueryInput",
    # sort
    "asc",
    "desc",
    # aggregates
    "avg",
    "sum",
    "count",
    "min",
    "max",
    "std",
    "variance",
    "median",
    "upper",
    "lower",
    "substring",
    "replace",
    "format",
    "percentile",
]
